### `Recommender system`

In [47]:
import numpy as np
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [48]:
pd.set_option("display.max_columns", 60)

In [49]:
df = pd.read_csv("D:/CODING/Virtual_py/PROJECTS/real_estate_ml/backend/kolkata/kolkata_cleaned_v5.csv")

In [50]:
df.head()

,PREFERENCE,DESCRIPTION,TRANSACT_TYPE,BEDROOM_NUM,AGE,TOTAL_FLOOR,PROP_NAME,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label,LATITUDE,LONGITUDE,Cooperative Society,Power of Attorney,Other,Leasehold,FACING_LABEL,FACING_label_North,FACING_label_North-East,FACING_label_North-West,FACING_label_Other,FACING_label_South,FACING_label_South-East,FACING_label_South-West,FACING_label_West,FURNISH_LABEL,FURNISH_label_Other,FURNISH_label_Semi-furnished,FURNISH_label_Unfurnished,PROPERTY_type,PROPERTY_TYPE_Independent/Builder Floor,PROPERTY_TYPE_Residential Apartment,PROPERTY_TYPE_Residential Land,CITY_LABELS,CITY_Kolkata East,CITY_Kolkata North,CITY_Kolkata South,CITY_Kolkata West,LANDMARK_DETAILS,CITY_NUM,LOCALITY
0,S,3bhk flat on the second floor of a four-Storey...,1.0,3.0,6,4.0,team taurus kabya,3 BHK Flat in Rajarhat,"['READY TO MOVE', 'RESALE', 'RERA | HIRA']",29.0,2.0,2.0,0.50,1287.0,3885.00,Cooperative Society,22.629509,88.479623,1,0,0,0,East,0,0,0,0,0,0,0,0,Fully furnished,0,0,0,Residential Apartment,0,1,0,Kolkata East,1,0,0,0,"['ReligiousPlace', 'Hospital', 'OfficeComplex'...",28,Rajarhat
1,S,"3bhk, 2 bath, semi-Furnished, 7th floor (Of 15...",1.0,3.0,2,15.0,eden city maheshtala,3 BHK Flat in Maheshtala,"['READY TO MOVE', 'RESALE', 'RERA | HIRA']",8.0,1.0,7.0,0.45,1377.0,3267.97,Cooperative Society,88.210954,22.493402,1,0,0,0,East,0,0,0,0,0,0,0,0,Other,1,0,0,Residential Apartment,0,1,0,Kolkata South,0,0,1,0,"['MetroStation', 'Shopping', 'Connectivity', '...",27,Maheshtala
2,S,3bhk flat/apartment for sale in baisnabghata b...,1.0,2.0,3,3.0,baisnabghata,2 BHK Flat in Baishnabghata Bye Lane,"['READY TO MOVE', 'RESALE']",48.0,4.0,3.0,0.35,810.0,4320.99,Cooperative Society,22.471111,88.372903,1,0,0,0,South-East,0,0,0,0,0,1,0,0,Other,1,0,0,Residential Apartment,0,1,0,Kolkata South,0,0,1,0,"['MetroStation', 'ReligiousPlace', 'ATM', 'Hos...",27,Baishnabghata Bye Lane
3,S,This is your chance to own a 3 bhk residential...,1.0,3.0,5,3.0,moana by varada group,3 BHK Flat in Raja SC Mallick ROAD,"['UNDER CONSTRUCTION', 'RESALE']",50.0,1.0,1.0,0.75,1208.0,6208.61,Cooperative Society,22.496720,88.370570,1,0,0,0,East,0,0,0,0,0,0,0,0,Fully furnished,0,0,0,Residential Apartment,0,1,0,Kolkata South,0,0,1,0,"['ReligiousPlace', 'Hospital', 'Attraction']",27,Raja SC Mallick ROAD
4,S,2bhk flat/apartment for sale in lake gardens c...,1.0,2.0,3,5.0,lake gardens chs,2 BHK Flat in Lake Gardens,"['READY TO MOVE', 'RESALE']",50.0,0.0,0.0,0.50,827.0,6045.95,Cooperative Society,22.505744,88.356716,1,0,0,0,North-West,0,0,1,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0,"['MetroStation', 'ReligiousPlace', 'ATM', 'Hos...",27,Lake Gardens

In [51]:
df.iloc[0].PREFERENCE

'S'

In [52]:
df.iloc[0].DESCRIPTION

'3bhk flat on the second floor of a four-Storey building of size 1287 square feet with a covered car park for one car in kabya residential complex in rajarhat, kolkata east. The apartment is new and ready to move. The project offers apartments with a perfect combination of contemporary architecture and features to provide comfortable living. It comprises of all world-Class amenities such as 24hrs water supply, 24hrs backup electricity, cctv cameras, community hall, compound, covered car parking, gated community, gym, jogging track, landscaped garden, lift, play area, security personnel and swimming pool. Kabya is strategically located in close proximity to all civic amenities such as schools, colleges, hospitals, shopping malls, grocery stores, restaurants, recreational centres etc. The complete address of kabya is water tank reckjoani, rajarhat, kolkata, west bengal, india.\n\nSpecification of the apartment\nLiving room: 3.61m x 3.17m\nDining: 3.89m x 2.66m\nKitchen: 2.46m x 2.18m\nBedroom 1: 3.84m x 3.38m\nBedroom 2: 3.61m x 3.38m\nBedroom 3: 3.76m x 2.90m\nToilet 1: 2.46m x 1.52\nToilet 2: 2.24m x 1.22m'

In [53]:
df.iloc[0].AGE

np.int64(6)

In [54]:
df.iloc[0].PROP_NAME

'team taurus kabya'

In [55]:
df.iloc[0].PROP_HEADING

'3 BHK Flat in Rajarhat'

In [56]:
df.iloc[0].SECONDARY_TAGS

"['READY TO MOVE', 'RESALE', 'RERA | HIRA']"

In [57]:
df.iloc[0].OWNTYPE_label

'Cooperative Society'

In [58]:
df.iloc[0].PRICE_Cr

np.float64(0.5)

In [59]:
df.iloc[0].AREA_SQFT

np.float64(1287.0)

In [60]:
df.iloc[0].FURNISH_LABEL

'Fully furnished'

In [61]:
df.iloc[0].PROPERTY_type

'Residential Apartment'

In [62]:
df.iloc[0].CITY_LABELS

'Kolkata East'

In [63]:
df.iloc[0].LANDMARK_DETAILS

"['ReligiousPlace', 'Hospital', 'OfficeComplex', 'BusDepot', 'Miscellaneous']"

In [64]:
df.iloc[0].LOCALITY

'Rajarhat'

In [65]:
new_df = df[[ "DESCRIPTION", "AGE", "PROP_NAME", "PROP_HEADING", "SECONDARY_TAGS", "LATITUDE","LONGITUDE","OWNTYPE_label","PRICE_Cr", "AREA_SQFT", "FURNISH_LABEL", "PROPERTY_type","CITY_LABELS", "LANDMARK_DETAILS", "LOCALITY"]]

In [66]:
new_df.head()

,DESCRIPTION,AGE,PROP_NAME,PROP_HEADING,SECONDARY_TAGS,LATITUDE,LONGITUDE,OWNTYPE_label,PRICE_Cr,AREA_SQFT,FURNISH_LABEL,PROPERTY_type,CITY_LABELS,LANDMARK_DETAILS,LOCALITY
0,3bhk flat on the second floor of a four-Storey...,6,team taurus kabya,3 BHK Flat in Rajarhat,"['READY TO MOVE', 'RESALE', 'RERA | HIRA']",22.629509,88.479623,Cooperative Society,0.50,1287.0,Fully furnished,Residential Apartment,Kolkata East,"['ReligiousPlace', 'Hospital', 'OfficeComplex'...",Rajarhat
1,"3bhk, 2 bath, semi-Furnished, 7th floor (Of 15...",2,eden city maheshtala,3 BHK Flat in Maheshtala,"['READY TO MOVE', 'RESALE', 'RERA | HIRA']",88.210954,22.493402,Cooperative Society,0.45,1377.0,Other,Residential Apartment,Kolkata South,"['MetroStation', 'Shopping', 'Connectivity', '...",Maheshtala
2,3bhk flat/apartment for sale in baisnabghata b...,3,baisnabghata,2 BHK Flat in Baishnabghata Bye Lane,"['READY TO MOVE', 'RESALE']",22.471111,88.372903,Cooperative Society,0.35,810.0,Other,Residential Apartment,Kolkata South,"['MetroStation', 'ReligiousPlace', 'ATM', 'Hos...",Baishnabghata Bye Lane
3,This is your chance to own a 3 bhk residential...,5,moana by varada group,3 BHK Flat in Raja SC Mallick ROAD,"['UNDER CONSTRUCTION', 'RESALE']",22.496720,88.370570,Cooperative Society,0.75,1208.0,Fully furnished,Residential Apartment,Kolkata South,"['ReligiousPlace', 'Hospital', 'Attraction']",Raja SC Mallick ROAD
4,2bhk flat/apartment for sale in lake gardens c...,3,lake gardens chs,2 BHK Flat in Lake Gardens,"['READY TO MOVE', 'RESALE']",22.505744,88.356716,Cooperative Society,0.50,827.0,Unfurnished,Residential Apartment,Kolkata South,"['MetroStation', 'ReligiousPlace', 'ATM', 'Hos...",Lake Gardens

In [67]:
description_df = new_df[["PROP_NAME", "DESCRIPTION","PROP_HEADING", "SECONDARY_TAGS", "LANDMARK_DETAILS", "FURNISH_LABEL", "PROPERTY_type", "OWNTYPE_label"]]

description_df.head()

,PROP_NAME,DESCRIPTION,PROP_HEADING,SECONDARY_TAGS,LANDMARK_DETAILS,FURNISH_LABEL,PROPERTY_type,OWNTYPE_label
0,team taurus kabya,3bhk flat on the second floor of a four-Storey...,3 BHK Flat in Rajarhat,"['READY TO MOVE', 'RESALE', 'RERA | HIRA']","['ReligiousPlace', 'Hospital', 'OfficeComplex'...",Fully furnished,Residential Apartment,Cooperative Society
1,eden city maheshtala,"3bhk, 2 bath, semi-Furnished, 7th floor (Of 15...",3 BHK Flat in Maheshtala,"['READY TO MOVE', 'RESALE', 'RERA | HIRA']","['MetroStation', 'Shopping', 'Connectivity', '...",Other,Residential Apartment,Cooperative Society
2,baisnabghata,3bhk flat/apartment for sale in baisnabghata b...,2 BHK Flat in Baishnabghata Bye Lane,"['READY TO MOVE', 'RESALE']","['MetroStation', 'ReligiousPlace', 'ATM', 'Hos...",Other,Residential Apartment,Cooperative Society
3,moana by varada group,This is your chance to own a 3 bhk residential...,3 BHK Flat in Raja SC Mallick ROAD,"['UNDER CONSTRUCTION', 'RESALE']","['ReligiousPlace', 'Hospital', 'Attraction']",Fully furnished,Residential Apartment,Cooperative Society
4,lake gardens chs,2bhk flat/apartment for sale in lake gardens c...,2 BHK Flat in Lake Gardens,"['READY TO MOVE', 'RESALE']","['MetroStation', 'ReligiousPlace', 'ATM', 'Hos...",Unfurnished,Residential Apartment,Cooperative Society

In [68]:
temp = description_df.copy()

In [69]:
description_df["LANDMARK_DETAILS"][0]

"['ReligiousPlace', 'Hospital', 'OfficeComplex', 'BusDepot', 'Miscellaneous']"

In [70]:
import ast

def extract_list(val):
    if pd.isna(val):
        return []
    try:
        parsed = ast.literal_eval(val)   # safely evaluate the string
        if isinstance(parsed, list):
            return parsed                # already a list
        else:
            return [parsed]              # wrap single values
    except (ValueError, SyntaxError):
        return []

In [71]:
description_df["LANDMARK_DETAILS"] = description_df["LANDMARK_DETAILS"].apply(extract_list)

In [72]:
description_df.head()

,PROP_NAME,DESCRIPTION,PROP_HEADING,SECONDARY_TAGS,LANDMARK_DETAILS,FURNISH_LABEL,PROPERTY_type,OWNTYPE_label
0,team taurus kabya,3bhk flat on the second floor of a four-Storey...,3 BHK Flat in Rajarhat,"['READY TO MOVE', 'RESALE', 'RERA | HIRA']","[ReligiousPlace, Hospital, OfficeComplex, BusD...",Fully furnished,Residential Apartment,Cooperative Society
1,eden city maheshtala,"3bhk, 2 bath, semi-Furnished, 7th floor (Of 15...",3 BHK Flat in Maheshtala,"['READY TO MOVE', 'RESALE', 'RERA | HIRA']","[MetroStation, Shopping, Connectivity, Educati...",Other,Residential Apartment,Cooperative Society
2,baisnabghata,3bhk flat/apartment for sale in baisnabghata b...,2 BHK Flat in Baishnabghata Bye Lane,"['READY TO MOVE', 'RESALE']","[MetroStation, ReligiousPlace, ATM, Hospital, ...",Other,Residential Apartment,Cooperative Society
3,moana by varada group,This is your chance to own a 3 bhk residential...,3 BHK Flat in Raja SC Mallick ROAD,"['UNDER CONSTRUCTION', 'RESALE']","[ReligiousPlace, Hospital, Attraction]",Fully furnished,Residential Apartment,Cooperative Society
4,lake gardens chs,2bhk flat/apartment for sale in lake gardens c...,2 BHK Flat in Lake Gardens,"['READY TO MOVE', 'RESALE']","[MetroStation, ReligiousPlace, ATM, Hospital]",Unfurnished,Residential Apartment,Cooperative Society

In [73]:
description_df["LANDMARK_DETAILS"][0]

['ReligiousPlace', 'Hospital', 'OfficeComplex', 'BusDepot', 'Miscellaneous']

In [74]:
description_df["LANDMARK_DETAILS_STR"] = description_df["LANDMARK_DETAILS"].apply(" ".join)

In [75]:
description_df["LANDMARK_DETAILS_STR"][0]

'ReligiousPlace Hospital OfficeComplex BusDepot Miscellaneous'

In [76]:
description_df.head()

,PROP_NAME,DESCRIPTION,PROP_HEADING,SECONDARY_TAGS,LANDMARK_DETAILS,FURNISH_LABEL,PROPERTY_type,OWNTYPE_label,LANDMARK_DETAILS_STR
0,team taurus kabya,3bhk flat on the second floor of a four-Storey...,3 BHK Flat in Rajarhat,"['READY TO MOVE', 'RESALE', 'RERA | HIRA']","[ReligiousPlace, Hospital, OfficeComplex, BusD...",Fully furnished,Residential Apartment,Cooperative Society,ReligiousPlace Hospital OfficeComplex BusDepot...
1,eden city maheshtala,"3bhk, 2 bath, semi-Furnished, 7th floor (Of 15...",3 BHK Flat in Maheshtala,"['READY TO MOVE', 'RESALE', 'RERA | HIRA']","[MetroStation, Shopping, Connectivity, Educati...",Other,Residential Apartment,Cooperative Society,MetroStation Shopping Connectivity Education H...
2,baisnabghata,3bhk flat/apartment for sale in baisnabghata b...,2 BHK Flat in Baishnabghata Bye Lane,"['READY TO MOVE', 'RESALE']","[MetroStation, ReligiousPlace, ATM, Hospital, ...",Other,Residential Apartment,Cooperative Society,MetroStation ReligiousPlace ATM Hospital Attra...
3,moana by varada group,This is your chance to own a 3 bhk residential...,3 BHK Flat in Raja SC Mallick ROAD,"['UNDER CONSTRUCTION', 'RESALE']","[ReligiousPlace, Hospital, Attraction]",Fully furnished,Residential Apartment,Cooperative Society,ReligiousPlace Hospital Attraction
4,lake gardens chs,2bhk flat/apartment for sale in lake gardens c...,2 BHK Flat in Lake Gardens,"['READY TO MOVE', 'RESALE']","[MetroStation, ReligiousPlace, ATM, Hospital]",Unfurnished,Residential Apartment,Cooperative Society,MetroStation ReligiousPlace ATM Hospital

In [77]:
description_df["SECONDARY_TAGS"] = description_df["SECONDARY_TAGS"].apply(extract_list)

description_df["SECONDARY_TAGS_STR"] = description_df["SECONDARY_TAGS"].apply(" ".join)

In [88]:
description_df.head(2)

,PROP_NAME,DESCRIPTION,PROP_HEADING,SECONDARY_TAGS,LANDMARK_DETAILS,FURNISH_LABEL,PROPERTY_type,OWNTYPE_label,LANDMARK_DETAILS_STR,SECONDARY_TAGS_STR,FACILITIES_TEXT
0,team taurus kabya,3bhk flat on the second floor of a four-Storey...,3 BHK Flat in Rajarhat,"[READY TO MOVE, RESALE, RERA | HIRA]","[ReligiousPlace, Hospital, OfficeComplex, BusD...",Fully furnished,Residential Apartment,Cooperative Society,ReligiousPlace Hospital OfficeComplex BusDepot...,READY TO MOVE RESALE RERA | HIRA,3bhk flat on the second floor of a four-Storey...
1,eden city maheshtala,"3bhk, 2 bath, semi-Furnished, 7th floor (Of 15...",3 BHK Flat in Maheshtala,"[READY TO MOVE, RESALE, RERA | HIRA]","[MetroStation, Shopping, Connectivity, Educati...",Other,Residential Apartment,Cooperative Society,MetroStation Shopping Connectivity Education H...,READY TO MOVE RESALE RERA | HIRA,"3bhk, 2 bath, semi-Furnished, 7th floor (Of 15..."

In [79]:
# Join relevant text columns into one string per row
description_df["FACILITIES_TEXT"] = (
    description_df["DESCRIPTION"].fillna("") + " " +
    description_df["PROP_HEADING"].fillna("") + " " +
    description_df["SECONDARY_TAGS_STR"].fillna("") + " " +
    description_df["LANDMARK_DETAILS_STR"].fillna("") + " " +
    description_df["FURNISH_LABEL"].fillna("") + " " +
    description_df["PROPERTY_type"].fillna("") + " " +
    description_df["OWNTYPE_label"].fillna("")
)

In [82]:
description_df.iloc[1].FACILITIES_TEXT

'3bhk, 2 bath, semi-Furnished, 7th floor (Of 15), at maheshtala location kolkata with covered car parking in very good condition. 3 BHK Flat in Maheshtala READY TO MOVE RESALE RERA | HIRA MetroStation Shopping Connectivity Education Hospital Airport RailwayStation Other Residential Apartment Cooperative Society'

In [83]:
# Apply TF-IDF
vectorizer = TfidfVectorizer(max_features=5000, stop_words='english', ngram_range=(1,2))
tfidf_matrix = vectorizer.fit_transform(description_df["FACILITIES_TEXT"])

In [84]:
tfidf_matrix.toarray().shape

(4515, 5000)

In [85]:
cosine_sim1 = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [86]:
cosine_sim1.shape

(4515, 4515)

In [90]:
def recommend_properties(property_name, cosine_sim = cosine_sim1):
    # get the index of the property
    idx = description_df.index[description_df["PROP_NAME"] == property_name].tolist()[0]

    # get the pairwise similarity scores for the property
    sim_scores = list(enumerate(cosine_sim[idx]))

    #sort the properties based on similarity scores
    sim_scores = sorted(sim_scores, key=lambda x : x[1], reverse = True)

    # get the scores of the top 10 properties
    sim_scores = sim_scores[1:11]

    # get the property indices
    property_indices = [i[0] for i in sim_scores]

    recommendation_df = pd.DataFrame({
        "Property Name" : description_df["PROP_NAME"].iloc[property_indices],
        "Similarity Scores" : sim_scores
    })

    return recommendation_df

In [91]:
description_df.head(5)

,PROP_NAME,DESCRIPTION,PROP_HEADING,SECONDARY_TAGS,LANDMARK_DETAILS,FURNISH_LABEL,PROPERTY_type,OWNTYPE_label,LANDMARK_DETAILS_STR,SECONDARY_TAGS_STR,FACILITIES_TEXT
0,team taurus kabya,3bhk flat on the second floor of a four-Storey...,3 BHK Flat in Rajarhat,"[READY TO MOVE, RESALE, RERA | HIRA]","[ReligiousPlace, Hospital, OfficeComplex, BusD...",Fully furnished,Residential Apartment,Cooperative Society,ReligiousPlace Hospital OfficeComplex BusDepot...,READY TO MOVE RESALE RERA | HIRA,3bhk flat on the second floor of a four-Storey...
1,eden city maheshtala,"3bhk, 2 bath, semi-Furnished, 7th floor (Of 15...",3 BHK Flat in Maheshtala,"[READY TO MOVE, RESALE, RERA | HIRA]","[MetroStation, Shopping, Connectivity, Educati...",Other,Residential Apartment,Cooperative Society,MetroStation Shopping Connectivity Education H...,READY TO MOVE RESALE RERA | HIRA,"3bhk, 2 bath, semi-Furnished, 7th floor (Of 15..."
2,baisnabghata,3bhk flat/apartment for sale in baisnabghata b...,2 BHK Flat in Baishnabghata Bye Lane,"[READY TO MOVE, RESALE]","[MetroStation, ReligiousPlace, ATM, Hospital, ...",Other,Residential Apartment,Cooperative Society,MetroStation ReligiousPlace ATM Hospital Attra...,READY TO MOVE RESALE,3bhk flat/apartment for sale in baisnabghata b...
3,moana by varada group,This is your chance to own a 3 bhk residential...,3 BHK Flat in Raja SC Mallick ROAD,"[UNDER CONSTRUCTION, RESALE]","[ReligiousPlace, Hospital, Attraction]",Fully furnished,Residential Apartment,Cooperative Society,ReligiousPlace Hospital Attraction,UNDER CONSTRUCTION RESALE,This is your chance to own a 3 bhk residential...
4,lake gardens chs,2bhk flat/apartment for sale in lake gardens c...,2 BHK Flat in Lake Gardens,"[READY TO MOVE, RESALE]","[MetroStation, ReligiousPlace, ATM, Hospital]",Unfurnished,Residential Apartment,Cooperative Society,MetroStation ReligiousPlace ATM Hospital,READY TO MOVE RESALE,2bhk flat/apartment for sale in lake gardens c...

In [92]:
recommend_properties("team taurus kabya")

                              Property Name            Similarity Scores
1379                        bijay residency  (1379, 0.27722402054635154)
600                                 the 102   (600, 0.26773991428833926)
4081                          urban greens    (4081, 0.2440708462681819)
2412                    unimark springfield  (2412, 0.24344523136771978)
4078                   urban greens phase 2  (4078, 0.24076502954744763)
1917                     swagatam apartment   (1917, 0.2222752461925475)
4085                   urban greens phase 2  (4085, 0.21324606611346106)
246                    realtech the indiana   (246, 0.21285844337462423)
35                        team taurus kabya    (35, 0.20055388017425727)
2266  west bengal housing millennium towers  (2266, 0.19170793415020063)

In [95]:

# Get the recommendation DataFrame
rec_df = recommend_properties("team taurus kabya")

# Extract indices from the Similarity Scores column
indices = [score[0] for score in rec_df["Similarity Scores"]]

# Use those indices to get full records
actual_records = description_df.iloc[indices]

actual_records.head()

,PROP_NAME,DESCRIPTION,PROP_HEADING,SECONDARY_TAGS,LANDMARK_DETAILS,FURNISH_LABEL,PROPERTY_type,OWNTYPE_label,LANDMARK_DETAILS_STR,SECONDARY_TAGS_STR,FACILITIES_TEXT
1379,bijay residency,"Bijay residency in kamalgazi, kolkata south is...",3 BHK Flat in Kamalgazi,"[READY TO MOVE, RESALE, RERA | HIRA]","[MetroStation, Connectivity, Education, Hospit...",Fully furnished,Residential Apartment,Cooperative Society,MetroStation Connectivity Education Hospital B...,READY TO MOVE RESALE RERA | HIRA,"Bijay residency in kamalgazi, kolkata south is..."
600,the 102,"The 102 in joka, kolkata south by ps group and...",3 BHK Flat in Joka,"[READY TO MOVE, RESALE, RERA | HIRA]","[MetroStation, Shopping, Connectivity, Educati...",Fully furnished,Residential Apartment,Cooperative Society,MetroStation Shopping Connectivity Education H...,READY TO MOVE RESALE RERA | HIRA,"The 102 in joka, kolkata south by ps group and..."
4081,urban greens,If you are looking to buy a new home in rajarh...,3 BHK Flat in Rajarhat,"[UNDER CONSTRUCTION, RESALE]","[ReligiousPlace, ATM, Hospital, OfficeComplex,...",Fully furnished,Residential Apartment,Cooperative Society,ReligiousPlace ATM Hospital OfficeComplex Park...,UNDER CONSTRUCTION RESALE,If you are looking to buy a new home in rajarh...
2412,unimark springfield,"Unimark springfield in rajarhat, kolkata east ...",3 BHK Flat in Rajarhat,"[UNDER CONSTRUCTION, RESALE, RERA | HIRA]","[Shopping, Connectivity, Education, Hospital, ...",Fully furnished,Residential Apartment,Cooperative Society,Shopping Connectivity Education Hospital Airpo...,UNDER CONSTRUCTION RESALE RERA | HIRA,"Unimark springfield in rajarhat, kolkata east ..."
4078,urban greens phase 2,If you are looking to buy a new home in rajarh...,2 BHK Flat in Rajarhat,"[UNDER CONSTRUCTION, RESALE, RERA | HIRA]","[MetroStation, Shopping, Education, Hospital, ...",Fully furnished,Residential Apartment,Cooperative Society,MetroStation Shopping Education Hospital Airpo...,UNDER CONSTRUCTION RESALE RERA | HIRA,If you are looking to buy a new home in rajarh...

Location → LATITUDE, LONGITUDE, CITY_LABELS, LOCALITY

Price → PRICE_Cr, AREA_SQFT, AGE

Facilities → DESCRIPTION, PROP_HEADING, SECONDARY_TAGS, LANDMARK_DETAILS, FURNISH_LABEL, PROPERTY_type, OWNTYPE_label

In [96]:
price_df = df[["PROP_NAME", "AGE", "BEDROOM_NUM", "BALCONY_NUM", "AREA_SQFT","PRICE_Cr"]]

In [97]:
price_df.head()

               PROP_NAME  AGE  BEDROOM_NUM  BALCONY_NUM  AREA_SQFT  PRICE_Cr
0      team taurus kabya    6          3.0          2.0     1287.0      0.50
1   eden city maheshtala    2          3.0          1.0     1377.0      0.45
2           baisnabghata    3          2.0          4.0      810.0      0.35
3  moana by varada group    5          3.0          1.0     1208.0      0.75
4       lake gardens chs    3          2.0          0.0      827.0      0.50

In [100]:
from sklearn.preprocessing import StandardScaler

# Numeric columns to scale
numeric_cols = ["AGE", "BEDROOM_NUM", "BALCONY_NUM", "AREA_SQFT", "PRICE_Cr"]

# Scale numeric features
scaler = StandardScaler()
scaled_values = scaler.fit_transform(price_df[numeric_cols])

# Build scaled DataFrame
scaled_df = pd.DataFrame(scaled_values, columns=numeric_cols, index=price_df.index)

In [101]:
scaled_df.head()

        AGE  BEDROOM_NUM  BALCONY_NUM  AREA_SQFT  PRICE_Cr
0  1.713407     0.535007     1.342612   0.098600 -0.374887
1 -0.268412     0.535007    -0.412162   0.263422 -0.447637
2  0.227042    -0.822173     4.852159  -0.774955 -0.593138
3  1.217952     0.535007    -0.412162  -0.046077 -0.011135
4  0.227042    -0.822173    -2.166936  -0.743822 -0.374887

In [102]:
cosine_sim_price = cosine_similarity(scaled_df, scaled_df)

In [103]:
cosine_sim_price.shape

(4515, 4515)

In [111]:
def recommend_properties_with_price(property_name):

    idx = price_df.index[price_df["PROP_NAME"] == property_name].tolist()[0]

    sim_scores = list(enumerate(cosine_sim_price[idx]))
    sim_scores = sorted(sim_scores, key = lambda x : x[1], reverse = True)
    sim_scores = sim_scores[1:11]

    property_indices = [i[0] for i in sim_scores]

    recomended_df = pd.DataFrame({
        "Property Name" : price_df["PROP_NAME"].iloc[property_indices],
        "Similarity Scores" : sim_scores
    })

    return recomended_df

In [112]:
recommend_properties_with_price("team taurus kabya")

                              Property Name           Similarity Scores
1690                      siddha waterfront  (1690, 0.9999198182185323)
3404                     biswas sudha tower  (3404, 0.9985895706012784)
4101   bloom tale coop. housing society ltd  (4101, 0.9979193553743455)
4098  bloom tale coop. housing society ltd.  (4098, 0.9978949090989614)
2006                                freshia  (2006, 0.9976309141785729)
3471                 netaji nagar, gachtala  (3471, 0.9975459896293174)
4018                             on request  (4018, 0.9975317511090431)
1705              reliable rabindra bhawan   (1705, 0.9973777483111238)
2921                        sd arun enclave  (2921, 0.9969272684372822)
1531                             southwinds  (1531, 0.9966398949997264)

In [113]:
# Get the recommendation DataFrame
rec_df = recommend_properties_with_price("team taurus kabya")

# Extract indices from the Similarity Scores column
indices = [score[0] for score in rec_df["Similarity Scores"]]

# Use those indices to get full records
actual_records = price_df.iloc[indices]

actual_records.head()

,PROP_NAME,AGE,BEDROOM_NUM,BALCONY_NUM,AREA_SQFT,PRICE_Cr
1690,siddha waterfront,6,3.0,2.0,1286.0,0.5200
3404,biswas sudha tower,6,3.0,2.0,1350.0,0.4725
4101,bloom tale coop. housing society ltd,6,3.0,2.0,1250.0,0.5900
4098,bloom tale coop. housing society ltd.,6,3.0,2.0,1249.0,0.5900
2006,freshia,6,3.0,2.0,1319.0,0.6000

In [114]:
location_df = df[["PROP_NAME", "LATITUDE", "LONGITUDE","CITY_LABELS", "LOCALITY"]]

In [115]:
location_df.head()

,PROP_NAME,LATITUDE,LONGITUDE,CITY_LABELS,LOCALITY
0,team taurus kabya,22.629509,88.479623,Kolkata East,Rajarhat
1,eden city maheshtala,88.210954,22.493402,Kolkata South,Maheshtala
2,baisnabghata,22.471111,88.372903,Kolkata South,Baishnabghata Bye Lane
3,moana by varada group,22.496720,88.370570,Kolkata South,Raja SC Mallick ROAD
4,lake gardens chs,22.505744,88.356716,Kolkata South,Lake Gardens

In [116]:
scaler = StandardScaler()
coords_scaled = scaler.fit_transform(location_df[["LATITUDE", "LONGITUDE"]])

In [117]:
# Compute similarity
cosine_sim_location = cosine_similarity(coords_scaled)

In [118]:
cosine_sim_location.shape

(4515, 4515)

In [133]:
def hybrid_recommend_properties_by_location(property_name, w_price=0.4, w_landnark=0.3, w_location=0.3,top_n=10):

    idx = location_df.index[location_df["PROP_NAME"] == property_name].tolist()[0]

    price_scores = cosine_sim_price[idx]
    landnark_scores = cosine_sim1[idx]
    location_scores = cosine_sim_location[idx]

    final_scores = (w_price * price_scores +
                    w_landnark * landnark_scores +
                    w_location * location_scores)
    
    sim_scores = list(enumerate(final_scores))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:top_n+1]

    property_indices = [i[0] for i in sim_scores]
    scores = [i[1] for i in sim_scores]

    recommended_df = pd.DataFrame({
    "Property Name": description_df["PROP_NAME"].iloc[property_indices].values,
    "Hybrid Score": scores
    }, index=property_indices)


    return recommended_df

In [140]:
hybrid_recommend_properties_by_location("team taurus kabya", 0, 0, 1)

                            Property Name  Hybrid Score
35                      team taurus kabya      1.000000
1330             shrachi greenwood sonata      1.000000
844          bhumi enclave, micheal nagar      0.999999
845   bhumi enclave, doltala jessore road      0.999999
2952                           on request      0.999999
2953                           on request      0.999999
2954                           on request      0.999999
3291                bhumi enclave doltala      0.999999
3292           bhumi enclave, madhyamgram      0.999999
3293           bhumi enclave, madhyamgram      0.999999

In [137]:
rec_df = hybrid_recommend_properties_by_location("team taurus kabya", 0, 0, 1)

# Extract indices from the Similarity Scores column
indices = rec_df.index.tolist()

# Use those indices to get full records
actual_records = df.iloc[indices][["PROP_NAME", "DESCRIPTION", "AGE", "PROP_HEADING", "SECONDARY_TAGS", "LATITUDE","LONGITUDE","OWNTYPE_label","PRICE_Cr", "AREA_SQFT", "FURNISH_LABEL", "PROPERTY_type","CITY_LABELS", "LANDMARK_DETAILS", "LOCALITY"]]

actual_records.head()

,PROP_NAME,DESCRIPTION,AGE,PROP_HEADING,SECONDARY_TAGS,LATITUDE,LONGITUDE,OWNTYPE_label,PRICE_Cr,AREA_SQFT,FURNISH_LABEL,PROPERTY_type,CITY_LABELS,LANDMARK_DETAILS,LOCALITY
35,team taurus kabya,Kabya is a brand new construction favorably lo...,6,2 BHK Flat in Rajarhat,"['READY TO MOVE', 'RESALE', 'RERA | HIRA']",22.629509,88.479623,Cooperative Society,0.3900,825.0,Fully furnished,Residential Apartment,Kolkata East,"['ReligiousPlace', 'Hospital', 'OfficeComplex'...",Rajarhat
1330,shrachi greenwood sonata,Shrachi greenwood sonata is one of kolkata eas...,2,2 BHK Flat in Noapara,"['READY TO MOVE', 'RESALE']",22.616942,88.448736,Cooperative Society,0.5500,770.0,Fully furnished,Residential Apartment,Kolkata East,"['ATM', 'Hospital', 'OfficeComplex', 'BusDepot']",Noapara
844,"bhumi enclave, micheal nagar",Spacious luxurious ready to move 2bhk availabl...,1,"2 BHK Flat in Michael nagar, Birati","['READY TO MOVE', 'RESALE']",22.630198,88.481660,Cooperative Society,0.2814,908.0,Fully furnished,Residential Apartment,Kolkata North,"['ReligiousPlace', 'Hospital', 'OfficeComplex'...","Michael nagar, Birati"
845,"bhumi enclave, doltala jessore road",Very spacious very luxurious 3 bhk available a...,1,3 BHK Flat in Madhyamgram,"['READY TO MOVE', 'RESALE']",22.630198,88.481660,Cooperative Society,0.3588,1158.0,Fully furnished,Residential Apartment,Kolkata North,"['ReligiousPlace', 'Hospital', 'OfficeComplex'...",Madhyamgram
2952,on request,"Situated in nayabad, kolkata south, on request...",1,3 BHK Flat in Nayabad,"['READY TO MOVE', 'RESALE']",22.630198,88.481660,Cooperative Society,0.5985,1330.0,Fully furnished,Residential Apartment,Kolkata South,"['ReligiousPlace', 'Hospital', 'OfficeComplex'...",Nayabad

In [138]:
df.duplicated().sum()

np.int64(2)

In [142]:
import pickle

pickle.dump(cosine_sim1, open("D:/CODING/Virtual_py/PROJECTS/real_estate_ml/backend/pkl/cosine_sim1.pkl", "wb"))
pickle.dump(cosine_sim_price, open("D:/CODING/Virtual_py/PROJECTS/real_estate_ml/backend/pkl/cosine_sim_price.pkl", "wb"))
pickle.dump(cosine_sim_location, open("D:/CODING/Virtual_py/PROJECTS/real_estate_ml/backend/pkl/cosine_sim_location.pkl", "wb"))

1. Dropdown prop_name
2. checkbox for locality, price, facilities
3. recommendation